[package]
name = "ataxx"
version = "0.1.0"
authors = ["FugEbinMeme <47312792+FugEbinMeme@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"